import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { FeedbackUiLayoutProvider } from "@/context";




const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Moha feedback App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
        crossOrigin="anonymous"
      />
      <script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossOrigin="anonymous"
      ></script>

      <script
        src="https://kit.fontawesome.com/b0e962578a.js"
        crossOrigin="anonymous"
      ></script>

      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link
        href="https://fonts.googleapis.com/css2?family=Work+Sans:ital,wght@0,100..900;1,100..900&display=swap"
        rel="stylesheet"
      ></link>
      <body className={inter.className}>
        <FeedbackUiLayoutProvider >
           {children}
        </FeedbackUiLayoutProvider>
      </body>
    </html>
  );
}
